name: Sync Inventory Hourly
on:
  schedule:
    - cron: '45 * * * *'  # 45 min efter hver time
  workflow_dispatch:
jobs:
  sync-inventory:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests pandas
    
    - name: Sync inventory
      run: |
        python scripts/sync_inventory.py
    
    - name: Copy to docs folder for GitHub Pages
      run: |
        mkdir -p docs
        cp output/inventory_updates.csv docs/
        echo "Last updated: $(date)" > docs/inventory_status.txt
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        destination_dir: .  # Deploy til root af gh-pages
        keep_files: true    # Behold eksisterende filer (price_updates.csv)
    
    - name: Commit changes to main branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/inventory_updates.csv state/last_inventory.csv
        git commit -m "Inventory sync - $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
        git push
    
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Inventory sync failed',
            body: 'The hourly inventory sync workflow failed. Check the Actions tab for details.'
          })
